### ISSUE TITLE
function deployment failed

### ISSUE THREAD

**Issue by stunningric** [QUICK-GCP-LAB/2-Minutes-Labs-Solutions#34]
Hello Dude!, Just to inform you that below file where (4 places) we are deploying cloud functions please add "--no-gen2" switch. It is failing for long without clue. Thanks for great work.

https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/6a781c844aa01fcec1182c681fd8e018b6c6600e/Build%20an%20End-to-End%20Data%20Capture%20Pipeline%20using%20Document%20AI/gsp927-2.sh#L79

**Comment by QUICK-GCP-LAB** [comment]
Thanks for the information, i will update this code soon
