### ISSUE TITLE
Suggestion on Improvements in Cloning repo using git

### ISSUE THREAD

**Issue by anmol-fzr** [QUICK-GCP-LAB/2-Minutes-Labs-Solutions#40]
@Azso-Coder-Pro Hey I've used your scripts, Great work btw. I've red some your bash scripts and i this we can few improvements like passing arguments to git clone to clone repo's faster

```
--depth=1
--single-branch
--no-tags
--job=n
 ``` 
 these are the one that i think will help us the most. 
 
I would like to contribute and make appropriate changes to the code. Please let me know your thoughts on this.

**Comment by QUICK-GCP-LAB** [comment]
Can you contact me via LinkedIn ?
