### ISSUE TITLE
Problem in the specification of both firewall ruels in Create an Internal Load Balancer

### ISSUE THREAD

**Issue by Subhasis17** [QUICK-GCP-LAB/2-Minutes-Labs-Solutions#55]
### Problem in the specification of both firewall ruels

path - Create an Internal Load Balancer/gsp216.sh

1. **--source-ranges 0.0.0.0/0 \** 

(https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/e03f937009f84da92aaa4fd27c0df8e053f517a1/Create%20an%20Internal%20Load%20Balancer/gsp216.sh#L28)

In my lab  the range was 0.0.0.0/16 
I'm not sure if it is varying from lab to lab

------------------------------------------------------------------------------------------------------------------------------------------------------

2. **--network=default**

(https://github.com/QUICK-GCP-LAB/2-Minutes-Labs-Solutions/blob/e03f937009f84da92aaa4fd27c0df8e053f517a1/Create%20an%20Internal%20Load%20Balancer/gsp216.sh#L31)

In this line the network should be set to  "_my-internal-app_"  as per the lab

**Comment by QUICK-GCP-LAB** [comment]
Thanks for your information, I will update this lab solution soon.

**Comment by QUICK-GCP-LAB** [comment]
The New Commands is updated and I will upload its video solution tonight.

Thanks,
QUICK GCP LAB

**Comment by Subhasis17** [comment]
You are most welcome.....Your videos are a great help
Keep up bro
I'll inform you if I find anyother depreciated code

**Comment by QUICK-GCP-LAB** [comment]
Sure 😊
